/*
 * Serve JSON to our AngularJS client
 */
exports.countries = function (req, res) {
  res.json([
  			{
  				name: 'USA',
  				committees: [{name: 'DISEC', topics: [{name: "DISEC Topic 1"}, {name: "DISEC Topic 2"}]}, {name: 'SOCHUM', topics: [{name: "SOCHUM Topic 1"}, {name: "SOCHUM Topic 2"}]}, {name: 'FAO', topics: [{name: "FAO Topic 1"}, {name: "FAO Topic 2"}]}],
  			},
  			{
  				name: 'UK',
  				committees: [{name: 'DISEC', topics: [{name: "DISEC Topic 1"}, {name: "DISEC Topic 2"}]}, {name: 'SOCHUM', topics: [{name: "SOCHUM Topic 1"}, {name: "SOCHUM Topic 2"}]}],
  			},
        {
          name: 'France',
          committees: [{name: 'DISEC', topics: [{name: "DISEC Topic 1"}, {name: "DISEC Topic 2"}]}, {name: 'SOCHUM', topics: [{name: "SOCHUM Topic 1"}, {name: "SOCHUM Topic 2"}]}],
        },
  			]);
};

exports.phrases = function (req, res) {
  res.json({
    preambulatory: [
            "Affirming",
            "Alarmed by",
            "Approving",
            "Bearing in mind",
            "Believing",
            "Confident",
            "Contemplating",
            "Convinced",
            "Declaring",
            "Deeply concerned",
            "Deeply conscious",
            "Deeply convinced",
            "Deeply Disturbed",
            "Deeply Regretting",
            "Desiring",
            "Emphasizing",
            "Expecting",
            "Expecting",
            "Expressing it’s appreciation",
            "Fulfilling",
            "Fully aware",
            "Expecting",
            "Fulfilling",
            "Fully aware",
            "Further deploring",
            "Further recalling",
            "Guided by",
            "Having adopted",
            "Having considered",
            "Having examined",
            "Having received",
            "Keeping in mind",
            "Noting with deep concern",
            "Nothing with satisfaction",
            "Noting further",
            "Observing",
            "Reaffirming",
            "Realizing",
            "Recalling",
            "Recognizing",
            "Referring",
            "Seeking",
            "Taking into consideration",
            "Taking note",
            "Viewing with appreciation",
            "Welcoming",
            "Shreking"
            ],
    operative: [
            "Accepts",
            "Affirms",
            "Approves",
            "Authorizes",
            "Calls",
            "Calls upon",
            "Condemns",
            "Confirms",
            "Congratulates",
            "Considers",
            "Declares accordingly",
            "Deplores",
            "Designates",
            "Draws the attention",
            "Endorses",
            "Expresses its appreciation",
            "Expresses its hope",
            "Further invites",
            "Deplores",
            "Designates",
            "Draws the attention",
            "Emphasizes",
            "Encourages",
            "Expresses its appreciation",
            "Expresses its hope",
            "Further invites",
            "Further proclaims",
            "Further reminds Further recommends",
            "Further requests",
            "Further resolves",
            "Has resolved",
            "Notes",
            "Proclaims",
            "Reaffirms",
            "Recommends",
            "Regrets",
            "Reminds",
            "Requests",
            "Solemnly affirms",
            "Strongly condemns",
            "Supports",
            "Takes note of",
            "Transmits",
            "Trusts",
            "Shreking"]
  })
}